name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        image_name: skysider/pwndocker
        tag: latest
      run: docker build . --file Dockerfile --tag $image_name:$tag
    - name: login the docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWD }}
    - name: push the docker image
      run: docker push $image_name:$tag
        
